CC      = avr-gcc
WARN    = -Wall -Wextra
LDFLAGS = -lm
CFLAGS  = -Os -std=gnu99 -g -ggdb $(WARN)

BASE_SOURCES = io.c \
               platforms.c \
               usb.c \
               usb_config.c \
               usb_hardware.c \
	       timer.c \
	       time.c \
	       buttons.c \
               hid.c \
	       display.c \
	       gfx.c

TARGETS = techkeys

# Target: Techkeys card
OPTS_techkeys    = -mmcu=atmega16u2
SOURCES_techkeys = main_techkeys.c
RESULT_techkeys  = ukbdc_techkeys2-0.0
